### ISSUE TITLE
Only collapse regions with using directives, not using statements or declarations

### ISSUE THREAD

**Issue by Aldaviva** [duytech/AutoCollapseUsing#3]
As you may have seen, C# 8 introduced [`using` declarations](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement), which look like
```cs
using var reader = new StringReader(manyLines);
```

This syntax is similar enough to match the regular expression pattern `using .*;` in `AutoCollapseUsingListener.IsUsingRegion()`, causing methods which start with using declarations to collapse automatically.

For completeness, here are all the ways I have found that the `using` keyword can appear in C#.
|Keyword use|Example code|Current extension behavior|
|---|---|---|
|[Using directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)|<pre lang="cs">using MyNamespace;</pre>|✔ collapsed|
|[Using static directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static)|<pre lang="cs">using static MyNamespace;</pre>|✔ collapsed|
|[Using alias directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)|<pre lang="cs">using M = MyNamespace;</pre>|✔ collapsed|
|[Using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)|<pre lang="cs">using (var reader = new StringReader(manyLines)) {</pre>|✔ ignored|
|[Using declaration](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)|<pre lang="cs">using var reader = new StringReader(manyLines);</pre>|❌ collapsed|

I can submit a pull request with my proposed change.

**Comment by Aldaviva** [comment]
Pull request: #4

**Comment by duytech** [comment]
Thanks for this PR.

**Comment by Aldaviva** [comment]
You're welcome!
